# ------------------------------------------------------------------------------
# @Organization : Benjamin-Chung Lab
# @Project      : Environmental Risk Factors for Vivax Malaria in Peru
# @File         : 0-config.R
# @Description  : Shared configuration for all scripts: loads packages and
#                 defines paths. All paths default to local directories within
#                 this repository — no edits needed to run the pipeline with
#                 the provided public dataset.
# ------------------------------------------------------------------------------

# Load libraries ----------------------------------------------------------
library(dplyr)
library(magrittr)
library(purrr)
library(tidyr)
library(stringr)
library(ggplot2)
library(here)
library(glue)
library(data.table)
library(lubridate)
library(forestplot)
library(grid)
library(gridExtra)
library(cowplot)
library(lemon)
library(foreach)
library(parallel)
library(doParallel)

# Input data paths --------------------------------------------------------
# Public dataset (provided in this repository — no edits needed)
public_data_path <- paste0(here::here(), "/6-public-data/output/")

# Bootstrap results — generated by running 3-sherlock/ scripts
# After running, bootstrap .RDS files are saved here automatically
bs_path <- paste0(here::here(), "/bs/")

# Figure 2 only: requires non-public spatial raster data not included in
# this repository. Set this path if you have access to the original data.
# spatial_data_path <- "YOUR_SPATIAL_DATA_PATH"

# Output paths (all saved locally within the repository) ------------------
data_path    <- paste0(here::here(), "/data/")
results_path <- paste0(here::here(), "/results/")
tables_path  <- paste0(here::here(), "/tables/")
figure_path  <- paste0(here::here(), "/figures/")
